BEGIN TRANSACTION;
CREATE TABLE `domoticz_call_config` (
	`device_type`	INTEGER,
	`section`	INTEGER,
	`key`	INTEGER,
	`value`	INTEGER,
	PRIMARY KEY(`device_type`,`section`,`key`,`value`)
);
INSERT INTO `domoticz_call_config` (device_type, section, key, value) VALUES 
 ('scenes','api_call','type','scenes'),
 ('scenes','changeable','changeable','true'),
 ('scenes','icon','icon',':zap:'),
 ('scenes','respons','name','Name'),
 ('scenes','respons','status','Status'),
 ('scenes','respons','idx','idx'),
 ('scenes','respons','type','Type'),
 ('scenes','status_msg','name','name'),
 ('scenes','status_msg','status','status'),
 ('switches','api_call','type','devices'),
 ('switches','api_call','filter','light'),
 ('switches','api_call','used','true'),
 ('switches','api_call','order','Name'),
 ('switches','changeable','changeable','true'),
 ('switches','icon','icon',':bulb:'),
 ('switches','respons','name','Name'),
 ('switches','respons','status','Status'),
 ('switches','respons','idx','idx'),
 ('switches','respons','type','SwitchType'),
 ('switches','status_msg','name','name'),
 ('switches','status_msg','status','status'),
 ('utility','api_call','type','devices'),
 ('utility','api_call','filter','utility'),
 ('utility','api_call','used','true'),
 ('utility','api_call','order','Name'),
 ('utility','changeable','changeable','false'),
 ('utility','icon','icon',':electric_plug:'),
 ('utility','respons','name','Name'),
 ('utility','respons','usage','Usage'),
 ('utility','respons','today','CounterToday'),
 ('utility','respons','idx','idx'),
 ('utility','respons','type','Type'),
 ('utility','status_msg','name','name'),
 ('utility','status_msg','{CurrentUsage}','usage'),
 ('utility','status_msg','{UsageToday}','today'),
 ('temperature','api_call','type','devices'),
 ('temperature','api_call','filter','temp'),
 ('temperature','api_call','used','true'),
 ('temperature','api_call','order','Name'),
 ('temperature','changeable','changeable','false'),
 ('temperature','icon','icon',':chart_with_upwards_trend:'),
 ('temperature','respons','name','Name'),
 ('temperature','respons','type','Type'),
 ('temperature','respons','temperature','Temp'),
 ('temperature','respons','humidity','Humidity'),
 ('temperature','respons','idx','idx'),
 ('temperature','status_msg','name','name'),
 ('temperature','status_msg','{Temperature}','temperature'),
 ('temperature','status_msg','{Humidity}','humidity');
COMMIT;
